//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dome.R831a {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.partner.dome.fr/", ConfigurationName="R831a.DOME_BUS_EAI_R831aGetListAGGIRWS")]
    internal interface DOME_BUS_EAI_R831aGetListAGGIRWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(domeResponseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(domeCommonDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(domeDto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Dome.R831a.getListAGGIRResponse getListAGGIR(Dome.R831a.getListAGGIR request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class getListAGGIRDto : domeDto {
        
        private int benefProfileIdField;
        
        private bool benefProfileIdFieldSpecified;
        
        private int nbHistoricField;
        
        private bool nbHistoricFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int benefProfileId {
            get {
                return this.benefProfileIdField;
            }
            set {
                this.benefProfileIdField = value;
                this.RaisePropertyChanged("benefProfileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool benefProfileIdSpecified {
            get {
                return this.benefProfileIdFieldSpecified;
            }
            set {
                this.benefProfileIdFieldSpecified = value;
                this.RaisePropertyChanged("benefProfileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int nbHistoric {
            get {
                return this.nbHistoricField;
            }
            set {
                this.nbHistoricField = value;
                this.RaisePropertyChanged("nbHistoric");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nbHistoricSpecified {
            get {
                return this.nbHistoricFieldSpecified;
            }
            set {
                this.nbHistoricFieldSpecified = value;
                this.RaisePropertyChanged("nbHistoricSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getListAGGIRDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private domeHeaderDto dOME_headerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public domeHeaderDto DOME_header {
            get {
                return this.dOME_headerField;
            }
            set {
                this.dOME_headerField = value;
                this.RaisePropertyChanged("DOME_header");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeHeaderDto : domeCommonDto {
        
        private int deviceTypeField;
        
        private bool deviceTypeFieldSpecified;
        
        private string langueField;
        
        private string softwareNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int deviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
                this.RaisePropertyChanged("deviceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deviceTypeSpecified {
            get {
                return this.deviceTypeFieldSpecified;
            }
            set {
                this.deviceTypeFieldSpecified = value;
                this.RaisePropertyChanged("deviceTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string langue {
            get {
                return this.langueField;
            }
            set {
                this.langueField = value;
                this.RaisePropertyChanged("langue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string softwareName {
            get {
                return this.softwareNameField;
            }
            set {
                this.softwareNameField = value;
                this.RaisePropertyChanged("softwareName");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(domeResponseHeaderDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(domeHeaderDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeCommonDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
                this.RaisePropertyChanged("dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class aggirListItemDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int aGGIRGridIdField;
        
        private bool aGGIRGridIdFieldSpecified;
        
        private int structureProfileIdField;
        
        private bool structureProfileIdFieldSpecified;
        
        private string structureProfileStructureNameField;
        
        private System.DateTime aGGIREvaluationDateField;
        
        private bool aGGIREvaluationDateFieldSpecified;
        
        private int aGGIRCreationProfileIdField;
        
        private bool aGGIRCreationProfileIdFieldSpecified;
        
        private string aGGIRCreatorNameField;
        
        private System.DateTime aGGIRCreationDateField;
        
        private bool aGGIRCreationDateFieldSpecified;
        
        private string aGGIRCreatorEntityNameField;
        
        private string aGGIREvaluatorNameField;
        
        private int aGGIRCodeField;
        
        private bool aGGIRCodeFieldSpecified;
        
        private int aGGIRCoherenceField;
        
        private bool aGGIRCoherenceFieldSpecified;
        
        private int aGGIROrientationField;
        
        private bool aGGIROrientationFieldSpecified;
        
        private int aGGIRToiletteField;
        
        private bool aGGIRToiletteFieldSpecified;
        
        private int aGGIRHabillageField;
        
        private bool aGGIRHabillageFieldSpecified;
        
        private int aGGIRAlimentationField;
        
        private bool aGGIRAlimentationFieldSpecified;
        
        private int aGGIREliminationField;
        
        private bool aGGIREliminationFieldSpecified;
        
        private int aGGIRTransfertsField;
        
        private bool aGGIRTransfertsFieldSpecified;
        
        private int aGGIRDeplacIntField;
        
        private bool aGGIRDeplacIntFieldSpecified;
        
        private int aGGIRDeplacExtField;
        
        private bool aGGIRDeplacExtFieldSpecified;
        
        private int aGGIRAlerterField;
        
        private bool aGGIRAlerterFieldSpecified;
        
        private int aGGIRGestionField;
        
        private bool aGGIRGestionFieldSpecified;
        
        private int aGGIRCuisineField;
        
        private bool aGGIRCuisineFieldSpecified;
        
        private int aGGIRMenageField;
        
        private bool aGGIRMenageFieldSpecified;
        
        private int aGGIRTransportField;
        
        private bool aGGIRTransportFieldSpecified;
        
        private int aGGIRSuiviTraitementField;
        
        private bool aGGIRSuiviTraitementFieldSpecified;
        
        private int aGGIRTempsLibreField;
        
        private bool aGGIRTempsLibreFieldSpecified;
        
        private int aGGIRAchatsField;
        
        private bool aGGIRAchatsFieldSpecified;
        
        private string aGGIRCommentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int AGGIRGridId {
            get {
                return this.aGGIRGridIdField;
            }
            set {
                this.aGGIRGridIdField = value;
                this.RaisePropertyChanged("AGGIRGridId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRGridIdSpecified {
            get {
                return this.aGGIRGridIdFieldSpecified;
            }
            set {
                this.aGGIRGridIdFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRGridIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int structureProfileId {
            get {
                return this.structureProfileIdField;
            }
            set {
                this.structureProfileIdField = value;
                this.RaisePropertyChanged("structureProfileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool structureProfileIdSpecified {
            get {
                return this.structureProfileIdFieldSpecified;
            }
            set {
                this.structureProfileIdFieldSpecified = value;
                this.RaisePropertyChanged("structureProfileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string structureProfileStructureName {
            get {
                return this.structureProfileStructureNameField;
            }
            set {
                this.structureProfileStructureNameField = value;
                this.RaisePropertyChanged("structureProfileStructureName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime AGGIREvaluationDate {
            get {
                return this.aGGIREvaluationDateField;
            }
            set {
                this.aGGIREvaluationDateField = value;
                this.RaisePropertyChanged("AGGIREvaluationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIREvaluationDateSpecified {
            get {
                return this.aGGIREvaluationDateFieldSpecified;
            }
            set {
                this.aGGIREvaluationDateFieldSpecified = value;
                this.RaisePropertyChanged("AGGIREvaluationDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int AGGIRCreationProfileId {
            get {
                return this.aGGIRCreationProfileIdField;
            }
            set {
                this.aGGIRCreationProfileIdField = value;
                this.RaisePropertyChanged("AGGIRCreationProfileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRCreationProfileIdSpecified {
            get {
                return this.aGGIRCreationProfileIdFieldSpecified;
            }
            set {
                this.aGGIRCreationProfileIdFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRCreationProfileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string AGGIRCreatorName {
            get {
                return this.aGGIRCreatorNameField;
            }
            set {
                this.aGGIRCreatorNameField = value;
                this.RaisePropertyChanged("AGGIRCreatorName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime AGGIRCreationDate {
            get {
                return this.aGGIRCreationDateField;
            }
            set {
                this.aGGIRCreationDateField = value;
                this.RaisePropertyChanged("AGGIRCreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRCreationDateSpecified {
            get {
                return this.aGGIRCreationDateFieldSpecified;
            }
            set {
                this.aGGIRCreationDateFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRCreationDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string AGGIRCreatorEntityName {
            get {
                return this.aGGIRCreatorEntityNameField;
            }
            set {
                this.aGGIRCreatorEntityNameField = value;
                this.RaisePropertyChanged("AGGIRCreatorEntityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string AGGIREvaluatorName {
            get {
                return this.aGGIREvaluatorNameField;
            }
            set {
                this.aGGIREvaluatorNameField = value;
                this.RaisePropertyChanged("AGGIREvaluatorName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int AGGIRCode {
            get {
                return this.aGGIRCodeField;
            }
            set {
                this.aGGIRCodeField = value;
                this.RaisePropertyChanged("AGGIRCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRCodeSpecified {
            get {
                return this.aGGIRCodeFieldSpecified;
            }
            set {
                this.aGGIRCodeFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int AGGIRCoherence {
            get {
                return this.aGGIRCoherenceField;
            }
            set {
                this.aGGIRCoherenceField = value;
                this.RaisePropertyChanged("AGGIRCoherence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRCoherenceSpecified {
            get {
                return this.aGGIRCoherenceFieldSpecified;
            }
            set {
                this.aGGIRCoherenceFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRCoherenceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int AGGIROrientation {
            get {
                return this.aGGIROrientationField;
            }
            set {
                this.aGGIROrientationField = value;
                this.RaisePropertyChanged("AGGIROrientation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIROrientationSpecified {
            get {
                return this.aGGIROrientationFieldSpecified;
            }
            set {
                this.aGGIROrientationFieldSpecified = value;
                this.RaisePropertyChanged("AGGIROrientationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int AGGIRToilette {
            get {
                return this.aGGIRToiletteField;
            }
            set {
                this.aGGIRToiletteField = value;
                this.RaisePropertyChanged("AGGIRToilette");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRToiletteSpecified {
            get {
                return this.aGGIRToiletteFieldSpecified;
            }
            set {
                this.aGGIRToiletteFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRToiletteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int AGGIRHabillage {
            get {
                return this.aGGIRHabillageField;
            }
            set {
                this.aGGIRHabillageField = value;
                this.RaisePropertyChanged("AGGIRHabillage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRHabillageSpecified {
            get {
                return this.aGGIRHabillageFieldSpecified;
            }
            set {
                this.aGGIRHabillageFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRHabillageSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int AGGIRAlimentation {
            get {
                return this.aGGIRAlimentationField;
            }
            set {
                this.aGGIRAlimentationField = value;
                this.RaisePropertyChanged("AGGIRAlimentation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRAlimentationSpecified {
            get {
                return this.aGGIRAlimentationFieldSpecified;
            }
            set {
                this.aGGIRAlimentationFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRAlimentationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public int AGGIRElimination {
            get {
                return this.aGGIREliminationField;
            }
            set {
                this.aGGIREliminationField = value;
                this.RaisePropertyChanged("AGGIRElimination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIREliminationSpecified {
            get {
                return this.aGGIREliminationFieldSpecified;
            }
            set {
                this.aGGIREliminationFieldSpecified = value;
                this.RaisePropertyChanged("AGGIREliminationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public int AGGIRTransferts {
            get {
                return this.aGGIRTransfertsField;
            }
            set {
                this.aGGIRTransfertsField = value;
                this.RaisePropertyChanged("AGGIRTransferts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRTransfertsSpecified {
            get {
                return this.aGGIRTransfertsFieldSpecified;
            }
            set {
                this.aGGIRTransfertsFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRTransfertsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public int AGGIRDeplacInt {
            get {
                return this.aGGIRDeplacIntField;
            }
            set {
                this.aGGIRDeplacIntField = value;
                this.RaisePropertyChanged("AGGIRDeplacInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRDeplacIntSpecified {
            get {
                return this.aGGIRDeplacIntFieldSpecified;
            }
            set {
                this.aGGIRDeplacIntFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRDeplacIntSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public int AGGIRDeplacExt {
            get {
                return this.aGGIRDeplacExtField;
            }
            set {
                this.aGGIRDeplacExtField = value;
                this.RaisePropertyChanged("AGGIRDeplacExt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRDeplacExtSpecified {
            get {
                return this.aGGIRDeplacExtFieldSpecified;
            }
            set {
                this.aGGIRDeplacExtFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRDeplacExtSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public int AGGIRAlerter {
            get {
                return this.aGGIRAlerterField;
            }
            set {
                this.aGGIRAlerterField = value;
                this.RaisePropertyChanged("AGGIRAlerter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRAlerterSpecified {
            get {
                return this.aGGIRAlerterFieldSpecified;
            }
            set {
                this.aGGIRAlerterFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRAlerterSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public int AGGIRGestion {
            get {
                return this.aGGIRGestionField;
            }
            set {
                this.aGGIRGestionField = value;
                this.RaisePropertyChanged("AGGIRGestion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRGestionSpecified {
            get {
                return this.aGGIRGestionFieldSpecified;
            }
            set {
                this.aGGIRGestionFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRGestionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public int AGGIRCuisine {
            get {
                return this.aGGIRCuisineField;
            }
            set {
                this.aGGIRCuisineField = value;
                this.RaisePropertyChanged("AGGIRCuisine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRCuisineSpecified {
            get {
                return this.aGGIRCuisineFieldSpecified;
            }
            set {
                this.aGGIRCuisineFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRCuisineSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public int AGGIRMenage {
            get {
                return this.aGGIRMenageField;
            }
            set {
                this.aGGIRMenageField = value;
                this.RaisePropertyChanged("AGGIRMenage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRMenageSpecified {
            get {
                return this.aGGIRMenageFieldSpecified;
            }
            set {
                this.aGGIRMenageFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRMenageSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public int AGGIRTransport {
            get {
                return this.aGGIRTransportField;
            }
            set {
                this.aGGIRTransportField = value;
                this.RaisePropertyChanged("AGGIRTransport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRTransportSpecified {
            get {
                return this.aGGIRTransportFieldSpecified;
            }
            set {
                this.aGGIRTransportFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRTransportSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public int AGGIRSuiviTraitement {
            get {
                return this.aGGIRSuiviTraitementField;
            }
            set {
                this.aGGIRSuiviTraitementField = value;
                this.RaisePropertyChanged("AGGIRSuiviTraitement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRSuiviTraitementSpecified {
            get {
                return this.aGGIRSuiviTraitementFieldSpecified;
            }
            set {
                this.aGGIRSuiviTraitementFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRSuiviTraitementSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public int AGGIRTempsLibre {
            get {
                return this.aGGIRTempsLibreField;
            }
            set {
                this.aGGIRTempsLibreField = value;
                this.RaisePropertyChanged("AGGIRTempsLibre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRTempsLibreSpecified {
            get {
                return this.aGGIRTempsLibreFieldSpecified;
            }
            set {
                this.aGGIRTempsLibreFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRTempsLibreSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public int AGGIRAchats {
            get {
                return this.aGGIRAchatsField;
            }
            set {
                this.aGGIRAchatsField = value;
                this.RaisePropertyChanged("AGGIRAchats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGGIRAchatsSpecified {
            get {
                return this.aGGIRAchatsFieldSpecified;
            }
            set {
                this.aGGIRAchatsFieldSpecified = value;
                this.RaisePropertyChanged("AGGIRAchatsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string AGGIRComment {
            get {
                return this.aGGIRCommentField;
            }
            set {
                this.aGGIRCommentField = value;
                this.RaisePropertyChanged("AGGIRComment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getListAGGIRResponseDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeResponseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private domeResponseHeaderDto dOME_headerField;
        
        private int statusIdField;
        
        private bool statusIdFieldSpecified;
        
        private string statusUserMessageField;
        
        private string statusErrorMessageField;
        
        private string userMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public domeResponseHeaderDto DOME_header {
            get {
                return this.dOME_headerField;
            }
            set {
                this.dOME_headerField = value;
                this.RaisePropertyChanged("DOME_header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int statusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
                this.RaisePropertyChanged("statusId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusIdSpecified {
            get {
                return this.statusIdFieldSpecified;
            }
            set {
                this.statusIdFieldSpecified = value;
                this.RaisePropertyChanged("statusIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string statusUserMessage {
            get {
                return this.statusUserMessageField;
            }
            set {
                this.statusUserMessageField = value;
                this.RaisePropertyChanged("statusUserMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string statusErrorMessage {
            get {
                return this.statusErrorMessageField;
            }
            set {
                this.statusErrorMessageField = value;
                this.RaisePropertyChanged("statusErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string userMessage {
            get {
                return this.userMessageField;
            }
            set {
                this.userMessageField = value;
                this.RaisePropertyChanged("userMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeResponseHeaderDto : domeCommonDto {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class getListAGGIRResponseDto : domeResponseDto {
        
        private aggirListItemDto[] dOME_medAGGIRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DOME_medAGGIR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public aggirListItemDto[] DOME_medAGGIR {
            get {
                return this.dOME_medAGGIRField;
            }
            set {
                this.dOME_medAGGIRField = value;
                this.RaisePropertyChanged("DOME_medAGGIR");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListAGGIR", WrapperNamespace="http://webservices.partner.dome.fr/", IsWrapped=true)]
    internal partial class getListAGGIR {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.partner.dome.fr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dome.R831a.getListAGGIRDto arg0;
        
        public getListAGGIR() {
        }
        
        public getListAGGIR(Dome.R831a.getListAGGIRDto arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListAGGIRResponse", WrapperNamespace="http://webservices.partner.dome.fr/", IsWrapped=true)]
    internal partial class getListAGGIRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.partner.dome.fr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dome.R831a.getListAGGIRResponseDto @return;
        
        public getListAGGIRResponse() {
        }
        
        public getListAGGIRResponse(Dome.R831a.getListAGGIRResponseDto @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface DOME_BUS_EAI_R831aGetListAGGIRWSChannel : Dome.R831a.DOME_BUS_EAI_R831aGetListAGGIRWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class DOME_BUS_EAI_R831aGetListAGGIRWSClient : System.ServiceModel.ClientBase<Dome.R831a.DOME_BUS_EAI_R831aGetListAGGIRWS>, Dome.R831a.DOME_BUS_EAI_R831aGetListAGGIRWS {
        
        public DOME_BUS_EAI_R831aGetListAGGIRWSClient() {
        }
        
        public DOME_BUS_EAI_R831aGetListAGGIRWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DOME_BUS_EAI_R831aGetListAGGIRWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOME_BUS_EAI_R831aGetListAGGIRWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOME_BUS_EAI_R831aGetListAGGIRWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dome.R831a.getListAGGIRResponse Dome.R831a.DOME_BUS_EAI_R831aGetListAGGIRWS.getListAGGIR(Dome.R831a.getListAGGIR request) {
            return base.Channel.getListAGGIR(request);
        }
        
        public Dome.R831a.getListAGGIRResponseDto getListAGGIR(Dome.R831a.getListAGGIRDto arg0) {
            Dome.R831a.getListAGGIR inValue = new Dome.R831a.getListAGGIR();
            inValue.arg0 = arg0;
            Dome.R831a.getListAGGIRResponse retVal = ((Dome.R831a.DOME_BUS_EAI_R831aGetListAGGIRWS)(this)).getListAGGIR(inValue);
            return retVal.@return;
        }
    }
}
