//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dome.Service_References.R541b {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.partner.dome.fr/", ConfigurationName="R541b.DOME_BUS_EAI_R541bGetProfileListWS")]
    public interface DOME_BUS_EAI_R541bGetProfileListWS {
        
        // CODEGEN: Parameter 'authentificationResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(domeResponseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(domeCommonDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(domeDto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="authentificationResponse")]
        getProfileListWSResponse getProfileListWS(getProfileListWS request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<getProfileListWSResponse> getProfileListWSAsync(getProfileListWS request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class authentificationInputDto : domeDto {
        
        private int accountIdField;
        
        private bool accountIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
                this.RaisePropertyChanged("accountId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accountIdSpecified {
            get {
                return this.accountIdFieldSpecified;
            }
            set {
                this.accountIdFieldSpecified = value;
                this.RaisePropertyChanged("accountIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(authentificationInputDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private domeHeaderDto dOME_headerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public domeHeaderDto DOME_header {
            get {
                return this.dOME_headerField;
            }
            set {
                this.dOME_headerField = value;
                this.RaisePropertyChanged("DOME_header");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeHeaderDto : domeCommonDto {
        
        private int deviceTypeField;
        
        private bool deviceTypeFieldSpecified;
        
        private string langueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int deviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
                this.RaisePropertyChanged("deviceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deviceTypeSpecified {
            get {
                return this.deviceTypeFieldSpecified;
            }
            set {
                this.deviceTypeFieldSpecified = value;
                this.RaisePropertyChanged("deviceTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string langue {
            get {
                return this.langueField;
            }
            set {
                this.langueField = value;
                this.RaisePropertyChanged("langue");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(domeResponseHeaderDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(domeHeaderDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeCommonDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
                this.RaisePropertyChanged("dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class societyDataDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string societyNameField;
        
        private string societyRoadTypeField;
        
        private string societyRoadNameField;
        
        private string societyRoadNumberField;
        
        private string societyPostBoxField;
        
        private string societyLieuDitField;
        
        private string societyAddressComp1Field;
        
        private string societyAddressComp2Field;
        
        private string societyCedexField;
        
        private string societyCityZipCodeField;
        
        private string societyCityNameField;
        
        private string societyPhoneNumberField;
        
        private string societyEmailField;
        
        private string societyManagerLastNameField;
        
        private string societyManagerFirstNameField;
        
        private string societyURLField;
        
        private string societyLatitudeField;
        
        private string societyLongitudeField;
        
        private System.DateTime societyCreationDateField;
        
        private bool societyCreationDateFieldSpecified;
        
        private int societyCreationProfileIdField;
        
        private bool societyCreationProfileIdFieldSpecified;
        
        private System.DateTime societyUpdateDateField;
        
        private bool societyUpdateDateFieldSpecified;
        
        private int societyUpdateProfileIdField;
        
        private bool societyUpdateProfileIdFieldSpecified;
        
        private int typeSocietyConstanteIdField;
        
        private bool typeSocietyConstanteIdFieldSpecified;
        
        private int typeCivilityManagerConstanteIdField;
        
        private bool typeCivilityManagerConstanteIdFieldSpecified;
        
        private string societySIRENField;
        
        private string societySIRETField;
        
        private string societyFINESSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string societyName {
            get {
                return this.societyNameField;
            }
            set {
                this.societyNameField = value;
                this.RaisePropertyChanged("societyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string societyRoadType {
            get {
                return this.societyRoadTypeField;
            }
            set {
                this.societyRoadTypeField = value;
                this.RaisePropertyChanged("societyRoadType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string societyRoadName {
            get {
                return this.societyRoadNameField;
            }
            set {
                this.societyRoadNameField = value;
                this.RaisePropertyChanged("societyRoadName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string societyRoadNumber {
            get {
                return this.societyRoadNumberField;
            }
            set {
                this.societyRoadNumberField = value;
                this.RaisePropertyChanged("societyRoadNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string societyPostBox {
            get {
                return this.societyPostBoxField;
            }
            set {
                this.societyPostBoxField = value;
                this.RaisePropertyChanged("societyPostBox");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string societyLieuDit {
            get {
                return this.societyLieuDitField;
            }
            set {
                this.societyLieuDitField = value;
                this.RaisePropertyChanged("societyLieuDit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string societyAddressComp1 {
            get {
                return this.societyAddressComp1Field;
            }
            set {
                this.societyAddressComp1Field = value;
                this.RaisePropertyChanged("societyAddressComp1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string societyAddressComp2 {
            get {
                return this.societyAddressComp2Field;
            }
            set {
                this.societyAddressComp2Field = value;
                this.RaisePropertyChanged("societyAddressComp2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string societyCedex {
            get {
                return this.societyCedexField;
            }
            set {
                this.societyCedexField = value;
                this.RaisePropertyChanged("societyCedex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string societyCityZipCode {
            get {
                return this.societyCityZipCodeField;
            }
            set {
                this.societyCityZipCodeField = value;
                this.RaisePropertyChanged("societyCityZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string societyCityName {
            get {
                return this.societyCityNameField;
            }
            set {
                this.societyCityNameField = value;
                this.RaisePropertyChanged("societyCityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string societyPhoneNumber {
            get {
                return this.societyPhoneNumberField;
            }
            set {
                this.societyPhoneNumberField = value;
                this.RaisePropertyChanged("societyPhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string societyEmail {
            get {
                return this.societyEmailField;
            }
            set {
                this.societyEmailField = value;
                this.RaisePropertyChanged("societyEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string societyManagerLastName {
            get {
                return this.societyManagerLastNameField;
            }
            set {
                this.societyManagerLastNameField = value;
                this.RaisePropertyChanged("societyManagerLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string societyManagerFirstName {
            get {
                return this.societyManagerFirstNameField;
            }
            set {
                this.societyManagerFirstNameField = value;
                this.RaisePropertyChanged("societyManagerFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string societyURL {
            get {
                return this.societyURLField;
            }
            set {
                this.societyURLField = value;
                this.RaisePropertyChanged("societyURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string societyLatitude {
            get {
                return this.societyLatitudeField;
            }
            set {
                this.societyLatitudeField = value;
                this.RaisePropertyChanged("societyLatitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string societyLongitude {
            get {
                return this.societyLongitudeField;
            }
            set {
                this.societyLongitudeField = value;
                this.RaisePropertyChanged("societyLongitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public System.DateTime societyCreationDate {
            get {
                return this.societyCreationDateField;
            }
            set {
                this.societyCreationDateField = value;
                this.RaisePropertyChanged("societyCreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool societyCreationDateSpecified {
            get {
                return this.societyCreationDateFieldSpecified;
            }
            set {
                this.societyCreationDateFieldSpecified = value;
                this.RaisePropertyChanged("societyCreationDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public int societyCreationProfileId {
            get {
                return this.societyCreationProfileIdField;
            }
            set {
                this.societyCreationProfileIdField = value;
                this.RaisePropertyChanged("societyCreationProfileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool societyCreationProfileIdSpecified {
            get {
                return this.societyCreationProfileIdFieldSpecified;
            }
            set {
                this.societyCreationProfileIdFieldSpecified = value;
                this.RaisePropertyChanged("societyCreationProfileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public System.DateTime societyUpdateDate {
            get {
                return this.societyUpdateDateField;
            }
            set {
                this.societyUpdateDateField = value;
                this.RaisePropertyChanged("societyUpdateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool societyUpdateDateSpecified {
            get {
                return this.societyUpdateDateFieldSpecified;
            }
            set {
                this.societyUpdateDateFieldSpecified = value;
                this.RaisePropertyChanged("societyUpdateDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public int societyUpdateProfileId {
            get {
                return this.societyUpdateProfileIdField;
            }
            set {
                this.societyUpdateProfileIdField = value;
                this.RaisePropertyChanged("societyUpdateProfileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool societyUpdateProfileIdSpecified {
            get {
                return this.societyUpdateProfileIdFieldSpecified;
            }
            set {
                this.societyUpdateProfileIdFieldSpecified = value;
                this.RaisePropertyChanged("societyUpdateProfileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public int typeSocietyConstanteId {
            get {
                return this.typeSocietyConstanteIdField;
            }
            set {
                this.typeSocietyConstanteIdField = value;
                this.RaisePropertyChanged("typeSocietyConstanteId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSocietyConstanteIdSpecified {
            get {
                return this.typeSocietyConstanteIdFieldSpecified;
            }
            set {
                this.typeSocietyConstanteIdFieldSpecified = value;
                this.RaisePropertyChanged("typeSocietyConstanteIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public int typeCivilityManagerConstanteId {
            get {
                return this.typeCivilityManagerConstanteIdField;
            }
            set {
                this.typeCivilityManagerConstanteIdField = value;
                this.RaisePropertyChanged("typeCivilityManagerConstanteId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeCivilityManagerConstanteIdSpecified {
            get {
                return this.typeCivilityManagerConstanteIdFieldSpecified;
            }
            set {
                this.typeCivilityManagerConstanteIdFieldSpecified = value;
                this.RaisePropertyChanged("typeCivilityManagerConstanteIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string societySIREN {
            get {
                return this.societySIRENField;
            }
            set {
                this.societySIRENField = value;
                this.RaisePropertyChanged("societySIREN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string societySIRET {
            get {
                return this.societySIRETField;
            }
            set {
                this.societySIRETField = value;
                this.RaisePropertyChanged("societySIRET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string societyFINESS {
            get {
                return this.societyFINESSField;
            }
            set {
                this.societyFINESSField = value;
                this.RaisePropertyChanged("societyFINESS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class personDataDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string personFirstNameField;
        
        private string personLastNameField;
        
        private string personPhoneNumberField;
        
        private string personMobileNumberField;
        
        private string personRoadTypeField;
        
        private string personRoadNameField;
        
        private string personRoadNumberField;
        
        private string personPostBoxField;
        
        private string personLieuDitField;
        
        private string personAddressComp1Field;
        
        private string personAddressComp2Field;
        
        private string personCedexField;
        
        private string personCityZipCodeField;
        
        private string personCityNameField;
        
        private string personEmailField;
        
        private System.DateTime personBirthDateField;
        
        private bool personBirthDateFieldSpecified;
        
        private string personBirthNameField;
        
        private string personINSCField;
        
        private string personINSAField;
        
        private System.DateTime personCreationDateField;
        
        private bool personCreationDateFieldSpecified;
        
        private int personCreationProfileIdField;
        
        private bool personCreationProfileIdFieldSpecified;
        
        private string personUpdateDateField;
        
        private int personUpdateProfileIdField;
        
        private bool personUpdateProfileIdFieldSpecified;
        
        private int typeCivilityConstanteIdField;
        
        private bool typeCivilityConstanteIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string personFirstName {
            get {
                return this.personFirstNameField;
            }
            set {
                this.personFirstNameField = value;
                this.RaisePropertyChanged("personFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string personLastName {
            get {
                return this.personLastNameField;
            }
            set {
                this.personLastNameField = value;
                this.RaisePropertyChanged("personLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string personPhoneNumber {
            get {
                return this.personPhoneNumberField;
            }
            set {
                this.personPhoneNumberField = value;
                this.RaisePropertyChanged("personPhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string personMobileNumber {
            get {
                return this.personMobileNumberField;
            }
            set {
                this.personMobileNumberField = value;
                this.RaisePropertyChanged("personMobileNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string personRoadType {
            get {
                return this.personRoadTypeField;
            }
            set {
                this.personRoadTypeField = value;
                this.RaisePropertyChanged("personRoadType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string personRoadName {
            get {
                return this.personRoadNameField;
            }
            set {
                this.personRoadNameField = value;
                this.RaisePropertyChanged("personRoadName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string personRoadNumber {
            get {
                return this.personRoadNumberField;
            }
            set {
                this.personRoadNumberField = value;
                this.RaisePropertyChanged("personRoadNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string personPostBox {
            get {
                return this.personPostBoxField;
            }
            set {
                this.personPostBoxField = value;
                this.RaisePropertyChanged("personPostBox");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string personLieuDit {
            get {
                return this.personLieuDitField;
            }
            set {
                this.personLieuDitField = value;
                this.RaisePropertyChanged("personLieuDit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string personAddressComp1 {
            get {
                return this.personAddressComp1Field;
            }
            set {
                this.personAddressComp1Field = value;
                this.RaisePropertyChanged("personAddressComp1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string personAddressComp2 {
            get {
                return this.personAddressComp2Field;
            }
            set {
                this.personAddressComp2Field = value;
                this.RaisePropertyChanged("personAddressComp2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string personCedex {
            get {
                return this.personCedexField;
            }
            set {
                this.personCedexField = value;
                this.RaisePropertyChanged("personCedex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string personCityZipCode {
            get {
                return this.personCityZipCodeField;
            }
            set {
                this.personCityZipCodeField = value;
                this.RaisePropertyChanged("personCityZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string personCityName {
            get {
                return this.personCityNameField;
            }
            set {
                this.personCityNameField = value;
                this.RaisePropertyChanged("personCityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string personEmail {
            get {
                return this.personEmailField;
            }
            set {
                this.personEmailField = value;
                this.RaisePropertyChanged("personEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=15)]
        public System.DateTime personBirthDate {
            get {
                return this.personBirthDateField;
            }
            set {
                this.personBirthDateField = value;
                this.RaisePropertyChanged("personBirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personBirthDateSpecified {
            get {
                return this.personBirthDateFieldSpecified;
            }
            set {
                this.personBirthDateFieldSpecified = value;
                this.RaisePropertyChanged("personBirthDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string personBirthName {
            get {
                return this.personBirthNameField;
            }
            set {
                this.personBirthNameField = value;
                this.RaisePropertyChanged("personBirthName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string personINSC {
            get {
                return this.personINSCField;
            }
            set {
                this.personINSCField = value;
                this.RaisePropertyChanged("personINSC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string personINSA {
            get {
                return this.personINSAField;
            }
            set {
                this.personINSAField = value;
                this.RaisePropertyChanged("personINSA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public System.DateTime personCreationDate {
            get {
                return this.personCreationDateField;
            }
            set {
                this.personCreationDateField = value;
                this.RaisePropertyChanged("personCreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personCreationDateSpecified {
            get {
                return this.personCreationDateFieldSpecified;
            }
            set {
                this.personCreationDateFieldSpecified = value;
                this.RaisePropertyChanged("personCreationDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public int personCreationProfileId {
            get {
                return this.personCreationProfileIdField;
            }
            set {
                this.personCreationProfileIdField = value;
                this.RaisePropertyChanged("personCreationProfileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personCreationProfileIdSpecified {
            get {
                return this.personCreationProfileIdFieldSpecified;
            }
            set {
                this.personCreationProfileIdFieldSpecified = value;
                this.RaisePropertyChanged("personCreationProfileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string personUpdateDate {
            get {
                return this.personUpdateDateField;
            }
            set {
                this.personUpdateDateField = value;
                this.RaisePropertyChanged("personUpdateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public int personUpdateProfileId {
            get {
                return this.personUpdateProfileIdField;
            }
            set {
                this.personUpdateProfileIdField = value;
                this.RaisePropertyChanged("personUpdateProfileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personUpdateProfileIdSpecified {
            get {
                return this.personUpdateProfileIdFieldSpecified;
            }
            set {
                this.personUpdateProfileIdFieldSpecified = value;
                this.RaisePropertyChanged("personUpdateProfileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public int typeCivilityConstanteId {
            get {
                return this.typeCivilityConstanteIdField;
            }
            set {
                this.typeCivilityConstanteIdField = value;
                this.RaisePropertyChanged("typeCivilityConstanteId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeCivilityConstanteIdSpecified {
            get {
                return this.typeCivilityConstanteIdFieldSpecified;
            }
            set {
                this.typeCivilityConstanteIdFieldSpecified = value;
                this.RaisePropertyChanged("typeCivilityConstanteIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class profileDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int profileIdField;
        
        private bool profileIdFieldSpecified;
        
        private int parentProfileIdField;
        
        private bool parentProfileIdFieldSpecified;
        
        private int typeStateConstanteIdField;
        
        private bool typeStateConstanteIdFieldSpecified;
        
        private int typeProfileConstanteIdField;
        
        private bool typeProfileConstanteIdFieldSpecified;
        
        private System.DateTime creationDateField;
        
        private bool creationDateFieldSpecified;
        
        private int creationProfileIdField;
        
        private bool creationProfileIdFieldSpecified;
        
        private personDataDto dOME_personDataField;
        
        private societyDataDto dOME_societyDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int profileId {
            get {
                return this.profileIdField;
            }
            set {
                this.profileIdField = value;
                this.RaisePropertyChanged("profileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool profileIdSpecified {
            get {
                return this.profileIdFieldSpecified;
            }
            set {
                this.profileIdFieldSpecified = value;
                this.RaisePropertyChanged("profileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int parentProfileId {
            get {
                return this.parentProfileIdField;
            }
            set {
                this.parentProfileIdField = value;
                this.RaisePropertyChanged("parentProfileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parentProfileIdSpecified {
            get {
                return this.parentProfileIdFieldSpecified;
            }
            set {
                this.parentProfileIdFieldSpecified = value;
                this.RaisePropertyChanged("parentProfileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int typeStateConstanteId {
            get {
                return this.typeStateConstanteIdField;
            }
            set {
                this.typeStateConstanteIdField = value;
                this.RaisePropertyChanged("typeStateConstanteId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeStateConstanteIdSpecified {
            get {
                return this.typeStateConstanteIdFieldSpecified;
            }
            set {
                this.typeStateConstanteIdFieldSpecified = value;
                this.RaisePropertyChanged("typeStateConstanteIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int typeProfileConstanteId {
            get {
                return this.typeProfileConstanteIdField;
            }
            set {
                this.typeProfileConstanteIdField = value;
                this.RaisePropertyChanged("typeProfileConstanteId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeProfileConstanteIdSpecified {
            get {
                return this.typeProfileConstanteIdFieldSpecified;
            }
            set {
                this.typeProfileConstanteIdFieldSpecified = value;
                this.RaisePropertyChanged("typeProfileConstanteIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime creationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("creationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationDateSpecified {
            get {
                return this.creationDateFieldSpecified;
            }
            set {
                this.creationDateFieldSpecified = value;
                this.RaisePropertyChanged("creationDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int creationProfileId {
            get {
                return this.creationProfileIdField;
            }
            set {
                this.creationProfileIdField = value;
                this.RaisePropertyChanged("creationProfileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationProfileIdSpecified {
            get {
                return this.creationProfileIdFieldSpecified;
            }
            set {
                this.creationProfileIdFieldSpecified = value;
                this.RaisePropertyChanged("creationProfileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public personDataDto DOME_personData {
            get {
                return this.dOME_personDataField;
            }
            set {
                this.dOME_personDataField = value;
                this.RaisePropertyChanged("DOME_personData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public societyDataDto DOME_societyData {
            get {
                return this.dOME_societyDataField;
            }
            set {
                this.dOME_societyDataField = value;
                this.RaisePropertyChanged("DOME_societyData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(authentificationResponseDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeResponseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private domeResponseHeaderDto dOME_headerField;
        
        private int statusIdField;
        
        private bool statusIdFieldSpecified;
        
        private string statusUserMessageField;
        
        private string statusErrorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public domeResponseHeaderDto DOME_header {
            get {
                return this.dOME_headerField;
            }
            set {
                this.dOME_headerField = value;
                this.RaisePropertyChanged("DOME_header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int statusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
                this.RaisePropertyChanged("statusId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusIdSpecified {
            get {
                return this.statusIdFieldSpecified;
            }
            set {
                this.statusIdFieldSpecified = value;
                this.RaisePropertyChanged("statusIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string statusUserMessage {
            get {
                return this.statusUserMessageField;
            }
            set {
                this.statusUserMessageField = value;
                this.RaisePropertyChanged("statusUserMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string statusErrorMessage {
            get {
                return this.statusErrorMessageField;
            }
            set {
                this.statusErrorMessageField = value;
                this.RaisePropertyChanged("statusErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeResponseHeaderDto : domeCommonDto {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class authentificationResponseDto : domeResponseDto {
        
        private bool firstConnexionField;
        
        private bool firstConnexionFieldSpecified;
        
        private profileDto[] dOME_profileListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool FirstConnexion {
            get {
                return this.firstConnexionField;
            }
            set {
                this.firstConnexionField = value;
                this.RaisePropertyChanged("FirstConnexion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstConnexionSpecified {
            get {
                return this.firstConnexionFieldSpecified;
            }
            set {
                this.firstConnexionFieldSpecified = value;
                this.RaisePropertyChanged("FirstConnexionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DOME_profileList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public profileDto[] DOME_profileList {
            get {
                return this.dOME_profileListField;
            }
            set {
                this.dOME_profileListField = value;
                this.RaisePropertyChanged("DOME_profileList");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProfileListWS", WrapperNamespace="http://webservices.partner.dome.fr/", IsWrapped=true)]
    public partial class getProfileListWS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.partner.dome.fr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public authentificationInputDto arg0;
        
        public getProfileListWS() {
        }
        
        public getProfileListWS(authentificationInputDto arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProfileListWSResponse", WrapperNamespace="http://webservices.partner.dome.fr/", IsWrapped=true)]
    public partial class getProfileListWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.partner.dome.fr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public authentificationResponseDto authentificationResponse;
        
        public getProfileListWSResponse() {
        }
        
        public getProfileListWSResponse(authentificationResponseDto authentificationResponse) {
            this.authentificationResponse = authentificationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DOME_BUS_EAI_R541bGetProfileListWSChannel : DOME_BUS_EAI_R541bGetProfileListWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DOME_BUS_EAI_R541bGetProfileListWSClient : System.ServiceModel.ClientBase<DOME_BUS_EAI_R541bGetProfileListWS>, DOME_BUS_EAI_R541bGetProfileListWS {
        
        public DOME_BUS_EAI_R541bGetProfileListWSClient() {
        }
        
        public DOME_BUS_EAI_R541bGetProfileListWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DOME_BUS_EAI_R541bGetProfileListWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOME_BUS_EAI_R541bGetProfileListWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOME_BUS_EAI_R541bGetProfileListWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getProfileListWSResponse DOME_BUS_EAI_R541bGetProfileListWS.getProfileListWS(getProfileListWS request) {
            return base.Channel.getProfileListWS(request);
        }
        
        public authentificationResponseDto getProfileListWS(authentificationInputDto arg0) {
            getProfileListWS inValue = new getProfileListWS();
            inValue.arg0 = arg0;
            getProfileListWSResponse retVal = ((DOME_BUS_EAI_R541bGetProfileListWS)(this)).getProfileListWS(inValue);
            return retVal.authentificationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getProfileListWSResponse> DOME_BUS_EAI_R541bGetProfileListWS.getProfileListWSAsync(getProfileListWS request) {
            return base.Channel.getProfileListWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<getProfileListWSResponse> getProfileListWSAsync(authentificationInputDto arg0) {
            getProfileListWS inValue = new getProfileListWS();
            inValue.arg0 = arg0;
            return ((DOME_BUS_EAI_R541bGetProfileListWS)(this)).getProfileListWSAsync(inValue);
        }
    }
}
