//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dome.Service_References.R823 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.partner.dome.fr/", ConfigurationName="R823.DOME_BUS_EAI_R823setDetailJourneyEntryWS")]
    public interface DOME_BUS_EAI_R823setDetailJourneyEntryWS {
        
        // CODEGEN: Parameter 'alterCourseEntryResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(domeCommonDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(domeDto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="alterCourseEntryResponse")]
        alterCourseEntryResponse alterCourseEntry(alterCourseEntry request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<alterCourseEntryResponse> alterCourseEntryAsync(alterCourseEntry request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class alterCourseEntryDto : addCourseEntryDto {
        
        private int parcoursPatientIdField;
        
        private bool parcoursPatientIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int parcoursPatientId {
            get {
                return this.parcoursPatientIdField;
            }
            set {
                this.parcoursPatientIdField = value;
                this.RaisePropertyChanged("parcoursPatientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parcoursPatientIdSpecified {
            get {
                return this.parcoursPatientIdFieldSpecified;
            }
            set {
                this.parcoursPatientIdFieldSpecified = value;
                this.RaisePropertyChanged("parcoursPatientIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(alterCourseEntryDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class addCourseEntryDto : domeDto {
        
        private int benefProfileIdField;
        
        private bool benefProfileIdFieldSpecified;
        
        private courseEntryDto dOME_parcoursPatientField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int benefProfileId {
            get {
                return this.benefProfileIdField;
            }
            set {
                this.benefProfileIdField = value;
                this.RaisePropertyChanged("benefProfileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool benefProfileIdSpecified {
            get {
                return this.benefProfileIdFieldSpecified;
            }
            set {
                this.benefProfileIdFieldSpecified = value;
                this.RaisePropertyChanged("benefProfileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public courseEntryDto DOME_parcoursPatient {
            get {
                return this.dOME_parcoursPatientField;
            }
            set {
                this.dOME_parcoursPatientField = value;
                this.RaisePropertyChanged("DOME_parcoursPatient");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class courseEntryDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime eventDateField;
        
        private bool eventDateFieldSpecified;
        
        private int sensParcoursIdField;
        
        private bool sensParcoursIdFieldSpecified;
        
        private string structureNameField;
        
        private string structureRoadTypeField;
        
        private string structureRoadNameField;
        
        private string structureRoadNumberField;
        
        private string structurePostBoxField;
        
        private string structureLieuDitField;
        
        private string structureAddressComp1Field;
        
        private string structureAddressComp2Field;
        
        private string structureCedexField;
        
        private int structureCityZipCodeField;
        
        private bool structureCityZipCodeFieldSpecified;
        
        private string structureCityNameField;
        
        private string structurePhoneField;
        
        private int structureServiceIdField;
        
        private bool structureServiceIdFieldSpecified;
        
        private string infoStructureAccueilField;
        
        private int admissionTypeIdField;
        
        private bool admissionTypeIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime eventDate {
            get {
                return this.eventDateField;
            }
            set {
                this.eventDateField = value;
                this.RaisePropertyChanged("eventDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventDateSpecified {
            get {
                return this.eventDateFieldSpecified;
            }
            set {
                this.eventDateFieldSpecified = value;
                this.RaisePropertyChanged("eventDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int sensParcoursId {
            get {
                return this.sensParcoursIdField;
            }
            set {
                this.sensParcoursIdField = value;
                this.RaisePropertyChanged("sensParcoursId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sensParcoursIdSpecified {
            get {
                return this.sensParcoursIdFieldSpecified;
            }
            set {
                this.sensParcoursIdFieldSpecified = value;
                this.RaisePropertyChanged("sensParcoursIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string structureName {
            get {
                return this.structureNameField;
            }
            set {
                this.structureNameField = value;
                this.RaisePropertyChanged("structureName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string structureRoadType {
            get {
                return this.structureRoadTypeField;
            }
            set {
                this.structureRoadTypeField = value;
                this.RaisePropertyChanged("structureRoadType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string structureRoadName {
            get {
                return this.structureRoadNameField;
            }
            set {
                this.structureRoadNameField = value;
                this.RaisePropertyChanged("structureRoadName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string structureRoadNumber {
            get {
                return this.structureRoadNumberField;
            }
            set {
                this.structureRoadNumberField = value;
                this.RaisePropertyChanged("structureRoadNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string structurePostBox {
            get {
                return this.structurePostBoxField;
            }
            set {
                this.structurePostBoxField = value;
                this.RaisePropertyChanged("structurePostBox");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string structureLieuDit {
            get {
                return this.structureLieuDitField;
            }
            set {
                this.structureLieuDitField = value;
                this.RaisePropertyChanged("structureLieuDit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string structureAddressComp1 {
            get {
                return this.structureAddressComp1Field;
            }
            set {
                this.structureAddressComp1Field = value;
                this.RaisePropertyChanged("structureAddressComp1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string structureAddressComp2 {
            get {
                return this.structureAddressComp2Field;
            }
            set {
                this.structureAddressComp2Field = value;
                this.RaisePropertyChanged("structureAddressComp2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string structureCedex {
            get {
                return this.structureCedexField;
            }
            set {
                this.structureCedexField = value;
                this.RaisePropertyChanged("structureCedex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int structureCityZipCode {
            get {
                return this.structureCityZipCodeField;
            }
            set {
                this.structureCityZipCodeField = value;
                this.RaisePropertyChanged("structureCityZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool structureCityZipCodeSpecified {
            get {
                return this.structureCityZipCodeFieldSpecified;
            }
            set {
                this.structureCityZipCodeFieldSpecified = value;
                this.RaisePropertyChanged("structureCityZipCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string structureCityName {
            get {
                return this.structureCityNameField;
            }
            set {
                this.structureCityNameField = value;
                this.RaisePropertyChanged("structureCityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string structurePhone {
            get {
                return this.structurePhoneField;
            }
            set {
                this.structurePhoneField = value;
                this.RaisePropertyChanged("structurePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int structureServiceId {
            get {
                return this.structureServiceIdField;
            }
            set {
                this.structureServiceIdField = value;
                this.RaisePropertyChanged("structureServiceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool structureServiceIdSpecified {
            get {
                return this.structureServiceIdFieldSpecified;
            }
            set {
                this.structureServiceIdFieldSpecified = value;
                this.RaisePropertyChanged("structureServiceIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string infoStructureAccueil {
            get {
                return this.infoStructureAccueilField;
            }
            set {
                this.infoStructureAccueilField = value;
                this.RaisePropertyChanged("infoStructureAccueil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public int admissionTypeId {
            get {
                return this.admissionTypeIdField;
            }
            set {
                this.admissionTypeIdField = value;
                this.RaisePropertyChanged("admissionTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool admissionTypeIdSpecified {
            get {
                return this.admissionTypeIdFieldSpecified;
            }
            set {
                this.admissionTypeIdFieldSpecified = value;
                this.RaisePropertyChanged("admissionTypeIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeResponseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private domeResponseHeaderDto dOME_headerField;
        
        private int statusIdField;
        
        private bool statusIdFieldSpecified;
        
        private string statusUserMessageField;
        
        private string statusErrorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public domeResponseHeaderDto DOME_header {
            get {
                return this.dOME_headerField;
            }
            set {
                this.dOME_headerField = value;
                this.RaisePropertyChanged("DOME_header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int statusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
                this.RaisePropertyChanged("statusId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusIdSpecified {
            get {
                return this.statusIdFieldSpecified;
            }
            set {
                this.statusIdFieldSpecified = value;
                this.RaisePropertyChanged("statusIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string statusUserMessage {
            get {
                return this.statusUserMessageField;
            }
            set {
                this.statusUserMessageField = value;
                this.RaisePropertyChanged("statusUserMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string statusErrorMessage {
            get {
                return this.statusErrorMessageField;
            }
            set {
                this.statusErrorMessageField = value;
                this.RaisePropertyChanged("statusErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeResponseHeaderDto : domeCommonDto {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(domeResponseHeaderDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(domeHeaderDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeCommonDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
                this.RaisePropertyChanged("dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeHeaderDto : domeCommonDto {
        
        private int deviceTypeField;
        
        private bool deviceTypeFieldSpecified;
        
        private string langueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int deviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
                this.RaisePropertyChanged("deviceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deviceTypeSpecified {
            get {
                return this.deviceTypeFieldSpecified;
            }
            set {
                this.deviceTypeFieldSpecified = value;
                this.RaisePropertyChanged("deviceTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string langue {
            get {
                return this.langueField;
            }
            set {
                this.langueField = value;
                this.RaisePropertyChanged("langue");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(addCourseEntryDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(alterCourseEntryDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private domeHeaderDto dOME_headerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public domeHeaderDto DOME_header {
            get {
                return this.dOME_headerField;
            }
            set {
                this.dOME_headerField = value;
                this.RaisePropertyChanged("DOME_header");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="alterCourseEntry", WrapperNamespace="http://webservices.partner.dome.fr/", IsWrapped=true)]
    public partial class alterCourseEntry {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.partner.dome.fr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public alterCourseEntryDto AlterCourseEntryDto;
        
        public alterCourseEntry() {
        }
        
        public alterCourseEntry(alterCourseEntryDto AlterCourseEntryDto) {
            this.AlterCourseEntryDto = AlterCourseEntryDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="alterCourseEntryResponse", WrapperNamespace="http://webservices.partner.dome.fr/", IsWrapped=true)]
    public partial class alterCourseEntryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="alterCourseEntryResponse", Namespace="http://webservices.partner.dome.fr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public domeResponseDto alterCourseEntryResponse1;
        
        public alterCourseEntryResponse() {
        }
        
        public alterCourseEntryResponse(domeResponseDto alterCourseEntryResponse1) {
            this.alterCourseEntryResponse1 = alterCourseEntryResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DOME_BUS_EAI_R823setDetailJourneyEntryWSChannel : DOME_BUS_EAI_R823setDetailJourneyEntryWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DOME_BUS_EAI_R823setDetailJourneyEntryWSClient : System.ServiceModel.ClientBase<DOME_BUS_EAI_R823setDetailJourneyEntryWS>, DOME_BUS_EAI_R823setDetailJourneyEntryWS {
        
        public DOME_BUS_EAI_R823setDetailJourneyEntryWSClient() {
        }
        
        public DOME_BUS_EAI_R823setDetailJourneyEntryWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DOME_BUS_EAI_R823setDetailJourneyEntryWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOME_BUS_EAI_R823setDetailJourneyEntryWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOME_BUS_EAI_R823setDetailJourneyEntryWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        alterCourseEntryResponse DOME_BUS_EAI_R823setDetailJourneyEntryWS.alterCourseEntry(alterCourseEntry request) {
            return base.Channel.alterCourseEntry(request);
        }
        
        public domeResponseDto alterCourseEntry(alterCourseEntryDto AlterCourseEntryDto) {
            alterCourseEntry inValue = new alterCourseEntry();
            inValue.AlterCourseEntryDto = AlterCourseEntryDto;
            alterCourseEntryResponse retVal = ((DOME_BUS_EAI_R823setDetailJourneyEntryWS)(this)).alterCourseEntry(inValue);
            return retVal.alterCourseEntryResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<alterCourseEntryResponse> DOME_BUS_EAI_R823setDetailJourneyEntryWS.alterCourseEntryAsync(alterCourseEntry request) {
            return base.Channel.alterCourseEntryAsync(request);
        }
        
        public System.Threading.Tasks.Task<alterCourseEntryResponse> alterCourseEntryAsync(alterCourseEntryDto AlterCourseEntryDto) {
            alterCourseEntry inValue = new alterCourseEntry();
            inValue.AlterCourseEntryDto = AlterCourseEntryDto;
            return ((DOME_BUS_EAI_R823setDetailJourneyEntryWS)(this)).alterCourseEntryAsync(inValue);
        }
    }
}
