//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dome.R213b {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.partner.dome.fr/", ConfigurationName="R213b.DOME_BUS_EAI_R213beventGetNotificationStructureWS")]
    public interface DOME_BUS_EAI_R213beventGetNotificationStructureWS {
        
        // CODEGEN: Parameter 'eventGetNotificationStructureResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(domeResponseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(domeCommonDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(domeDto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="eventGetNotificationStructureResponse")]
        Dome.R213b.getNotificationsResponse getNotifications(Dome.R213b.getNotifications request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Dome.R213b.getNotificationsResponse> getNotificationsAsync(Dome.R213b.getNotifications request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class eventGetNotificationStructureDto : domeDto {
        
        private int structureProfileIdField;
        
        private bool structureProfileIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int structureProfileId {
            get {
                return this.structureProfileIdField;
            }
            set {
                this.structureProfileIdField = value;
                this.RaisePropertyChanged("structureProfileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool structureProfileIdSpecified {
            get {
                return this.structureProfileIdFieldSpecified;
            }
            set {
                this.structureProfileIdFieldSpecified = value;
                this.RaisePropertyChanged("structureProfileIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(eventGetNotificationStructureDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private domeHeaderDto dOME_headerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public domeHeaderDto DOME_header {
            get {
                return this.dOME_headerField;
            }
            set {
                this.dOME_headerField = value;
                this.RaisePropertyChanged("DOME_header");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeHeaderDto : domeCommonDto {
        
        private int deviceTypeField;
        
        private bool deviceTypeFieldSpecified;
        
        private string langueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int deviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
                this.RaisePropertyChanged("deviceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deviceTypeSpecified {
            get {
                return this.deviceTypeFieldSpecified;
            }
            set {
                this.deviceTypeFieldSpecified = value;
                this.RaisePropertyChanged("deviceTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string langue {
            get {
                return this.langueField;
            }
            set {
                this.langueField = value;
                this.RaisePropertyChanged("langue");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(domeResponseHeaderDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(domeHeaderDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeCommonDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
                this.RaisePropertyChanged("dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class vacancyNotificationStructureDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int benefProfileIdField;
        
        private bool benefProfileIdFieldSpecified;
        
        private System.DateTime missingTimeStartField;
        
        private bool missingTimeStartFieldSpecified;
        
        private System.DateTime missingTimeEndField;
        
        private bool missingTimeEndFieldSpecified;
        
        private string commentaireField;
        
        private string motifField;
        
        private int notifVacancyProfileIdField;
        
        private bool notifVacancyProfileIdFieldSpecified;
        
        private string notifVacancyProfileNameField;
        
        private System.DateTime eventNotifDateTimeField;
        
        private bool eventNotifDateTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int benefProfileId {
            get {
                return this.benefProfileIdField;
            }
            set {
                this.benefProfileIdField = value;
                this.RaisePropertyChanged("benefProfileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool benefProfileIdSpecified {
            get {
                return this.benefProfileIdFieldSpecified;
            }
            set {
                this.benefProfileIdFieldSpecified = value;
                this.RaisePropertyChanged("benefProfileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime missingTimeStart {
            get {
                return this.missingTimeStartField;
            }
            set {
                this.missingTimeStartField = value;
                this.RaisePropertyChanged("missingTimeStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool missingTimeStartSpecified {
            get {
                return this.missingTimeStartFieldSpecified;
            }
            set {
                this.missingTimeStartFieldSpecified = value;
                this.RaisePropertyChanged("missingTimeStartSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime missingTimeEnd {
            get {
                return this.missingTimeEndField;
            }
            set {
                this.missingTimeEndField = value;
                this.RaisePropertyChanged("missingTimeEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool missingTimeEndSpecified {
            get {
                return this.missingTimeEndFieldSpecified;
            }
            set {
                this.missingTimeEndFieldSpecified = value;
                this.RaisePropertyChanged("missingTimeEndSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string commentaire {
            get {
                return this.commentaireField;
            }
            set {
                this.commentaireField = value;
                this.RaisePropertyChanged("commentaire");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string motif {
            get {
                return this.motifField;
            }
            set {
                this.motifField = value;
                this.RaisePropertyChanged("motif");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int notifVacancyProfileId {
            get {
                return this.notifVacancyProfileIdField;
            }
            set {
                this.notifVacancyProfileIdField = value;
                this.RaisePropertyChanged("notifVacancyProfileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool notifVacancyProfileIdSpecified {
            get {
                return this.notifVacancyProfileIdFieldSpecified;
            }
            set {
                this.notifVacancyProfileIdFieldSpecified = value;
                this.RaisePropertyChanged("notifVacancyProfileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string notifVacancyProfileName {
            get {
                return this.notifVacancyProfileNameField;
            }
            set {
                this.notifVacancyProfileNameField = value;
                this.RaisePropertyChanged("notifVacancyProfileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime eventNotifDateTime {
            get {
                return this.eventNotifDateTimeField;
            }
            set {
                this.eventNotifDateTimeField = value;
                this.RaisePropertyChanged("eventNotifDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventNotifDateTimeSpecified {
            get {
                return this.eventNotifDateTimeFieldSpecified;
            }
            set {
                this.eventNotifDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("eventNotifDateTimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class updateQueryNotificationStructureDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int benefProfileIdField;
        
        private bool benefProfileIdFieldSpecified;
        
        private int eventProIdMetierField;
        
        private bool eventProIdMetierFieldSpecified;
        
        private System.DateTime eventTimeStartField;
        
        private bool eventTimeStartFieldSpecified;
        
        private System.DateTime eventTimeEndField;
        
        private bool eventTimeEndFieldSpecified;
        
        private string commentaireField;
        
        private string motifField;
        
        private int eventNotifProfileIdField;
        
        private bool eventNotifProfileIdFieldSpecified;
        
        private string eventNotifProfileNameField;
        
        private System.DateTime eventNotifDateTimeField;
        
        private bool eventNotifDateTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int benefProfileId {
            get {
                return this.benefProfileIdField;
            }
            set {
                this.benefProfileIdField = value;
                this.RaisePropertyChanged("benefProfileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool benefProfileIdSpecified {
            get {
                return this.benefProfileIdFieldSpecified;
            }
            set {
                this.benefProfileIdFieldSpecified = value;
                this.RaisePropertyChanged("benefProfileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int eventProIdMetier {
            get {
                return this.eventProIdMetierField;
            }
            set {
                this.eventProIdMetierField = value;
                this.RaisePropertyChanged("eventProIdMetier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventProIdMetierSpecified {
            get {
                return this.eventProIdMetierFieldSpecified;
            }
            set {
                this.eventProIdMetierFieldSpecified = value;
                this.RaisePropertyChanged("eventProIdMetierSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime eventTimeStart {
            get {
                return this.eventTimeStartField;
            }
            set {
                this.eventTimeStartField = value;
                this.RaisePropertyChanged("eventTimeStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventTimeStartSpecified {
            get {
                return this.eventTimeStartFieldSpecified;
            }
            set {
                this.eventTimeStartFieldSpecified = value;
                this.RaisePropertyChanged("eventTimeStartSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime eventTimeEnd {
            get {
                return this.eventTimeEndField;
            }
            set {
                this.eventTimeEndField = value;
                this.RaisePropertyChanged("eventTimeEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventTimeEndSpecified {
            get {
                return this.eventTimeEndFieldSpecified;
            }
            set {
                this.eventTimeEndFieldSpecified = value;
                this.RaisePropertyChanged("eventTimeEndSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string commentaire {
            get {
                return this.commentaireField;
            }
            set {
                this.commentaireField = value;
                this.RaisePropertyChanged("commentaire");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string motif {
            get {
                return this.motifField;
            }
            set {
                this.motifField = value;
                this.RaisePropertyChanged("motif");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int eventNotifProfileId {
            get {
                return this.eventNotifProfileIdField;
            }
            set {
                this.eventNotifProfileIdField = value;
                this.RaisePropertyChanged("eventNotifProfileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventNotifProfileIdSpecified {
            get {
                return this.eventNotifProfileIdFieldSpecified;
            }
            set {
                this.eventNotifProfileIdFieldSpecified = value;
                this.RaisePropertyChanged("eventNotifProfileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string eventNotifProfileName {
            get {
                return this.eventNotifProfileNameField;
            }
            set {
                this.eventNotifProfileNameField = value;
                this.RaisePropertyChanged("eventNotifProfileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime eventNotifDateTime {
            get {
                return this.eventNotifDateTimeField;
            }
            set {
                this.eventNotifDateTimeField = value;
                this.RaisePropertyChanged("eventNotifDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventNotifDateTimeSpecified {
            get {
                return this.eventNotifDateTimeFieldSpecified;
            }
            set {
                this.eventNotifDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("eventNotifDateTimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(eventGetNotificationStructureResponseDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeResponseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private domeResponseHeaderDto dOME_headerField;
        
        private int statusIdField;
        
        private bool statusIdFieldSpecified;
        
        private string statusUserMessageField;
        
        private string statusErrorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public domeResponseHeaderDto DOME_header {
            get {
                return this.dOME_headerField;
            }
            set {
                this.dOME_headerField = value;
                this.RaisePropertyChanged("DOME_header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int statusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
                this.RaisePropertyChanged("statusId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusIdSpecified {
            get {
                return this.statusIdFieldSpecified;
            }
            set {
                this.statusIdFieldSpecified = value;
                this.RaisePropertyChanged("statusIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string statusUserMessage {
            get {
                return this.statusUserMessageField;
            }
            set {
                this.statusUserMessageField = value;
                this.RaisePropertyChanged("statusUserMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string statusErrorMessage {
            get {
                return this.statusErrorMessageField;
            }
            set {
                this.statusErrorMessageField = value;
                this.RaisePropertyChanged("statusErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class domeResponseHeaderDto : domeCommonDto {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.partner.dome.fr/")]
    public partial class eventGetNotificationStructureResponseDto : domeResponseDto {
        
        private updateQueryNotificationStructureDto[] dOME_updateQuieryListField;
        
        private vacancyNotificationStructureDto[] dOME_vacancyListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DOME_updateQuieryList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public updateQueryNotificationStructureDto[] DOME_updateQuieryList {
            get {
                return this.dOME_updateQuieryListField;
            }
            set {
                this.dOME_updateQuieryListField = value;
                this.RaisePropertyChanged("DOME_updateQuieryList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DOME_vacancyList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public vacancyNotificationStructureDto[] DOME_vacancyList {
            get {
                return this.dOME_vacancyListField;
            }
            set {
                this.dOME_vacancyListField = value;
                this.RaisePropertyChanged("DOME_vacancyList");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNotifications", WrapperNamespace="http://webservices.partner.dome.fr/", IsWrapped=true)]
    public partial class getNotifications {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.partner.dome.fr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dome.R213b.eventGetNotificationStructureDto eventGetNotificationStructureDto;
        
        public getNotifications() {
        }
        
        public getNotifications(Dome.R213b.eventGetNotificationStructureDto eventGetNotificationStructureDto) {
            this.eventGetNotificationStructureDto = eventGetNotificationStructureDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNotificationsResponse", WrapperNamespace="http://webservices.partner.dome.fr/", IsWrapped=true)]
    public partial class getNotificationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.partner.dome.fr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dome.R213b.eventGetNotificationStructureResponseDto eventGetNotificationStructureResponse;
        
        public getNotificationsResponse() {
        }
        
        public getNotificationsResponse(Dome.R213b.eventGetNotificationStructureResponseDto eventGetNotificationStructureResponse) {
            this.eventGetNotificationStructureResponse = eventGetNotificationStructureResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DOME_BUS_EAI_R213beventGetNotificationStructureWSChannel : Dome.R213b.DOME_BUS_EAI_R213beventGetNotificationStructureWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DOME_BUS_EAI_R213beventGetNotificationStructureWSClient : System.ServiceModel.ClientBase<Dome.R213b.DOME_BUS_EAI_R213beventGetNotificationStructureWS>, Dome.R213b.DOME_BUS_EAI_R213beventGetNotificationStructureWS {
        
        public DOME_BUS_EAI_R213beventGetNotificationStructureWSClient() {
        }
        
        public DOME_BUS_EAI_R213beventGetNotificationStructureWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DOME_BUS_EAI_R213beventGetNotificationStructureWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOME_BUS_EAI_R213beventGetNotificationStructureWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOME_BUS_EAI_R213beventGetNotificationStructureWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dome.R213b.getNotificationsResponse Dome.R213b.DOME_BUS_EAI_R213beventGetNotificationStructureWS.getNotifications(Dome.R213b.getNotifications request) {
            return base.Channel.getNotifications(request);
        }
        
        public Dome.R213b.eventGetNotificationStructureResponseDto getNotifications(Dome.R213b.eventGetNotificationStructureDto eventGetNotificationStructureDto) {
            Dome.R213b.getNotifications inValue = new Dome.R213b.getNotifications();
            inValue.eventGetNotificationStructureDto = eventGetNotificationStructureDto;
            Dome.R213b.getNotificationsResponse retVal = ((Dome.R213b.DOME_BUS_EAI_R213beventGetNotificationStructureWS)(this)).getNotifications(inValue);
            return retVal.eventGetNotificationStructureResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dome.R213b.getNotificationsResponse> Dome.R213b.DOME_BUS_EAI_R213beventGetNotificationStructureWS.getNotificationsAsync(Dome.R213b.getNotifications request) {
            return base.Channel.getNotificationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dome.R213b.getNotificationsResponse> getNotificationsAsync(Dome.R213b.eventGetNotificationStructureDto eventGetNotificationStructureDto) {
            Dome.R213b.getNotifications inValue = new Dome.R213b.getNotifications();
            inValue.eventGetNotificationStructureDto = eventGetNotificationStructureDto;
            return ((Dome.R213b.DOME_BUS_EAI_R213beventGetNotificationStructureWS)(this)).getNotificationsAsync(inValue);
        }
    }
}
